Kentobot 5.0 (#12)
* Fix JS Error

* Fixed BTTVAPIv3

* Docs updates

* Improve guides page
Fixed active class not always applying on page load if menu parsing is slow
Added the ability to use the URI Hash to direct link specific guides

* twitchembeds guide

* Update toc.json

* Update twitchembeds.md

* Added support for remote panel getting webauth via cookie, skipping panelConfig

* Refactored docs/panel/login to support webauth cookie method
Removed default panelConfig from docs/panel
Updated docs/panel/js/utils/helpers to save the entire hashmap for all scripts to use
Added better feedback to docs/panel and docs/panel/login when the selectedbot hash parameter is missing
Added promisePoll to docs/panel/js/utils/helpers

* Setup WsPanelHandler for remote retrival without HTTP
Add TwitchCache.getDisplayName
Add new panelConfig for docs/panel

* Implemented WS load of panelSettings for docs/panel

* Update links for /game and /(get-)lang in /docs/panel

* Fix hashmap key check

* Fix WS load check

* Fix ajax order on docs/panel/login
Add debug output for /sslcheck and /checkwsload

* Updated docs/panel/index.js to use /sslcheck when initing ws
Fixed /sslcheck in /docs/panel/login
Added ability for ws to detect a 403/SSL Required resposne and switch

* Fix parsing of ws messages

* Fix Exception on remote wsload auth

* Fix remote socket message

* Fix main styles throughout /docs

* Fix missing quote

* Fix darkmode on /docs/panel

* Fix dataTables
Fix customizations to AdminLTE

* Fix typo

* Fix icon sizes

* Update skins

* Fix window location

* Fixed bot links
Fixed CORS missing from HttpSslRedirectHandler

* Fix null origin

* Default useHttps to false again

* Theme Update

* Update error messages for embeds on built-in copy of panel
Remove /checkwsload
Revert /docs version of panel to trying https first

* Add update guide

* Change status for WsSslErrorHandler to 426

* Fix toc

* Added WsPanelRemoteLoginHandler

* Remove no longer neccessary wsload stuff
Update structure of remote queries
Protect lang file save from being committed when using RO auth
Added socket.doRemote
Stripped old connection methods from /docs/panel

* Remove webauth via cookie and /panel/login/remote

* Finish setup of ws login for remote panel

* Win setup guide

* Add macos, centos

* Fixed bootstrap.min.css having an integrity check added that would fail

* Fix pace css
Debugging login

* Fix login box color on dark theme

* Fix login

* fix(Dockerfile): [[ needs bash, java needs +x

* fix(docker-compose.yml): build block

optionally build docker image locally (remove comment chars)

* Switch back to https
Added WebSocket close frames
Added guide links to built-in panel SSL error messages
Added support for invalidateAuthorization to WsSharedRWTokenAuthenticationHandler
Added proper closure of WS Sessions on bot shutdown

* Fixed GitHubAPIv3 to give the correct release for the current OS, when possible

* Remove matrix builds on workflows in favor of ubuntu-latest only

* Update guides/twitchembeds

* Updatge Copyrights

* Version bump
Update Dockerfile to take ARG in for the version

* Add ANT_ARGS and standard ant arguments to Dockerfile

* Fixed Dockerfile attempting to chmod non-existent file in ARM builds

* feat: use .env file for secrets

* feat: add caddy

* use .env file to set DOMAIN (localhost is used as fallback)
* caddy automatically generates self-signed certificate for that domain

* chore: do not expose phantombot anymore

* chore: add build args to docker-compose.yml

* Discord Integration Setup

* Fixed security vulnerability with URI's

* Fixed pathing errors resulting in Exceptions
Added missing allowed path to HTTPNoAuthHandler

* Fix PhantomBot.GetExecutionPath returning an invalid Path due to extra slash added on Windows

* Fixed remaining pathing issues with URI jailing
Added debug output for 404 on WS and HTTP paths with no handler

* Version Bump

* Update Setup guide

* Update discordintegrationsetup.md

* Cyrillic support

Cyrillic support for customapi/customapijson

* Adjusted relative links to local js/css to prevent 404

* Fix js string vs java string bug in link whitelist

* Adjusted verion number for case sensitive keyword migration to 3.3.0

* Create CNAME

* Delete CNAME

* Create CNAME

* Updated CNAME

Included alternative website URL, as well as more sub-domains.

* Fix oauth bootstrap css import

* Update links

* Update links
Fix guides error

* Update links
Remove no longer used classes

* Add stubs for upcoming guides

* Attempt to fix user logo in remote panel

* Fix js for user logo

* Fix transmission of logo

* Fixed remote panel logo

* Added ability to send message as the bot from Dashboard

* Version bump

* Delete brand.png

* Add files via upload

* use viewercard url instead of channel url

* Fixed linux guides missing chmod on launch-service.sh
Fixed Ubuntu guide showing the systemd service as one-liners

* Add documentation for register chat command function

* Add documentation for sanitize function

* Add new pages in toc.json

* Minor corrections to register chat command doc

* Twitch command list, Discord command list and FAQ from old website

* Addition of Twitch/Discord command list and FAQ from website and start of developer information docs.

* Correct missed line in toc

* Update toc.json

* Update toc.json

* Update faq.md

* Update twitchembeds.md

Fixed some text edits for the guides page.

* Update commands.md

* Fix LangFileUpdater

* Fix links TypeError: Cannot find function matchAll

* Fix remote panel lang editor and games auto-complete

* Fix missing async

* Try to fix games search
Fix logo on built-in panel

* Fixed the games drop-down for remote panel

* Fix inconsistent output from (pointtouser)
Change (pointtouser) to resolve the target username

* Added GamesListUpdater
Added HttpResponse.toString

* Change GamesListUpdater to throw out the original file on initial load

* Fixed java.lang.ArrayIndexOutOfBoundsException caused by multi-part message starting with a PONG
Fixed potential for a multi-part message starting with a PING or PONG to cause the other messages to be ignored
closes PhantomBot/PhantomBot#2321

* - Added command variables.

* Fix command variable guide
Add alternating bnackgrounds to table rows

* Line spacing in guide

* Update twitchembeds.md

Added NGINX sample config.

* Update CNAME

* Update README.md

* WIP

* Channel points integration in java-script. Actions possible are: transfer (spend channel points to get bot points), give all (spend channel points to give everyone bot points), emote-only (put chat into emote only for a period of time) and timeout (timeout a user).

* Addition of setup documentation.

* Bug fix for user input for channel points timeout function

* Bug fix for channel points functions duration / amount setup for invalid values

* Addition of channel points troubleshooting

* Channel points handler improvements for input validation and improved configuration.

* Add toc to module guides. Add Discord link to channel points troubleshooting.

* Channel points bug fix to clear ID when config entered.

* Add channel points future TODO

* Removed references to cbenni.com

* Update links

* Manual merge PhantomBot/PhantomBot#2324 by @nastayaval

* Add OBS instructions to twitchembeds.md
Add NGINX comments

* Fixing Phantom.bot not scrollable on mobile

- Changed index to reflect default AdminLTE base
- Added AdminLTE.js and SRI
- Remove currently useless Nav-Button on Mobile

* - Added dark theme.

* - More dark theme work.

* - Guides dark theme.

* - Dark mode for code blocks

* - Fixed sidebar dark mode

* Update AdminLTE.dark.min.css

* Added full update logic and debugging output to GamesListUpdater

* Restored ability to subscribe to chat_moderator_actions using a non-broadcaster OAuth
Changed PubSub to shutdown until restart if both topics fail to subscribe
Added proper handling for PubSub RECONNECT message
Fixed GamesListUpdater not running on edge/custom builds

* Use documented PubSub topic when apioauth is from broadcaster

* Added launch-jdb.bat to development-resources

* Grammar

* Fix timing of GameListUpdater

* Added ExponentialBackoff

* Remove unneccessary logic

* Added ExponentialBackoff.GetTotalIterations

* Implemented ExponentialBackoff in TwitchPubSub

* Guide toc.json update

* Update remote panel keywords.js to match changes in PhantomBot/PhantomBot#2246

* Adding Twitter Integration Guide.

* Update twitterintegration.md

* Update twitterintegration.md

* Adding Youtube Integration Guide

* Update youtubesetup.md

* use utf8mb4 charset with mysql so emojis can be stored directly in database

* Fixed (playsound) not accepting the number 0 in the audio hook name
closes PhantomBot/PhantomBot#2331

* Fixed DiscordUtil.getUserAsync returning empty Mono when lookup parameter was an @mention

* Fixed roleManager not handling java.util.NoSuchElementException when calling DiscordUtil.getRoleAsync and DiscordUtil.getUserAsync
Fixed DiscordUtil.getUserAsync returning empty Mono when lookup parameter was an @mention
Fixed DiscordUtil.getRoleAsync returning empty Mono when lookup parameter was an @mention
Fixed java.lang.UnsupportedOperationException when calling DiscordUtil.editUserRoles

* Fix CustomCommands.transformers.buildArgs returning raw:true when using (1|def) tag, which could cause unintended tag parsing if there is () in the default value

* We're always making Changes and improvments to Spotif .... Phantombot

- Added Tipeeestream Integration Guide
- Added Streamelements Integration Guide
- Created Subfolder for Integrations (since it's getting more and more)
- Changed Order from Random to possible Setup order

* Create console-commands.md

* Update toc.json

* Added missing glyphicons

* Force tag name from matcher result to lowercase to prevent tag failure

* Fix debug statements in callHook@init.js

* Fixed incorrect RegEx for buildArgs()@customCommands.js:123 causing escapeTags()@customCommands.js:78 TypeError: Cannot call method "replace" of undefine

* Fixed RegEx for (customapijson) causing it to not function

* Added ability to specify localTransformers to tags@customCommands.js for the current call only
Added ability to disable the global transformers to tags@customCommands.js for current call only

* Added the ability to add/replace a global tag transformer

* Made parameter atEnabled optional (default false) in tags()@customCommands.js

* Added default return when command is undefined in getCommandScript()@commandRegsiter.js
closes PhantomBot/PhantomBot#2337

* Added Ping/Pong system to YT WS with a 12 second window to kill connections
Added WebSocketFrameHandler.getWsSessions(uri)
closes gmt2001/PhantomBot-1#136

* Added warning when accessing YT Player with an IP as the URL hostname
closes gmt2001/PhantomBot-1#100

* Create SECURITY.md

* Update index.html

* Update index.html

* Update index.html

* Change Dockerfile build to use official adoptopenjdk bionic images as base

* Update index.html

* Update index.html

* Added Remember Me option to remote panel login
closes PhantomBot/PhantomBot#2338

* Update copyright

* Version bump

* random number limits was missing

* Kentobot 5.0 changes

Co-authored-by: gmt2001 <garymt2001@hotmail.com>
Co-authored-by: gmt2001 <gmt2001@users.noreply.github.com>
Co-authored-by: nastayaval <nastayberezovskaya@gmail.com>
Co-authored-by: nastayaval <67388974+nastayaval@users.noreply.github.com>
Co-authored-by: Phillip Stockmann <mail@phillip-stockmann.de>
Co-authored-by: Branden B <18152900+BrandenB@users.noreply.github.com>
Co-authored-by: Ethan O'Donnell <ethan@ejpo.io>
Co-authored-by: Robsdedude <robsdedude@googlemail.com>
Co-authored-by: Zackery Messier <zackery@zackery.tv>
Co-authored-by: Zackery M <zelakto@zelakto.tv>
Co-authored-by: emilweth <coucou@emi.cool>
Co-authored-by: MzLiv <mzlivstreams@gmail.com>
Co-authored-by: MzLiv <mzlivstream@gmail.com>
Co-authored-by: Matt Demers <matt@mattdemers.com>
Co-authored-by: Sándor Fodor <alex@digitaltrip.hu>
Co-authored-by: tooti <tooti312@gmail.com>
Co-authored-by: tooti31 <49535223+tooti31@users.noreply.github.com>