Import sys in healthcheck.py
Fixes this error:

```
$ python3 ./healthcheck.py
Restarting phantombot due to failure lastalive...
Traceback (most recent call last):
  File "./healthcheck.py", line 127, in <module>
    dofailure("lastalive", "Last alive timestamp has expired")
  File "./healthcheck.py", line 41, in dofailure
    print("Health Check Failed (" + type + "):" + message, file=sys.stderr)
NameError: name 'sys' is not defined
```